Repository DarkMessiah27/2.PzD-Mission-Template, pull requests merged in 2021-11, with the labels that each got.

#4 Remove unused mARMAcp code
  missions/2PzD_Template_v3_0.VR/description.ext
Labels: invalid

#5 Update gearUS42.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/US/gearUS42.sqf
Labels: v3.0 Phase 2

#15 Changes to Russian Loadouts
  missions/2PzD_Template_v3_0.VR/customization/loadouts/Russian/gearRus41.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/Russian/gearRus44.sqf
Labels: v3.0 Phase 2

#16 GearDef rework
  compositions/!2PzD_DAK_41/composition.sqe
  compositions/!2PzD_DAK_41/header.sqe
  compositions/!2PzD_DAK_42/composition.sqe
  compositions/!2PzD_DAK_42/header.sqe
  missions/2PzD_Template_v3_0.VR/core/description.hpp
  missions/2PzD_Template_v3_0.VR/customization/gearLoadouts.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/! DONT DELETE THESE !.txt
  missions/2PzD_Template_v3_0.VR/customization/geardefs/! DONT DELETE THESE/! DONT DELETE THESE !.txt
  missions/2PzD_Template_v3_0.VR/customization/geardefs/British/gearDefUK.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/German/gearDefGerAfrica.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/German/gearDefGerLuft.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/German/gearDefGerMisc.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/German/gearDefGerRegular.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/German/gearDefGerWeapons.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/German/gearDefGerWinter.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/Japanese/gearDefJap.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/Russian/gearDefRus.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/US/gearDefUS.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/gearDefGer.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearDAK41.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearDAK42.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearWHR44.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/Japanese/gearJpn42.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/Japanese/gearJpn44.sqf
  missions/2PzD_Template_v3_0.VR/customization/vehicleGearLoadouts.sqf
Labels: v3.0 Phase 1

#21 Equipment sets
  missions/2PzD_Template_v3_0.VR/customization/gearLoadouts.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/Generic/gearDefEquipmentSets.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/Generic/gearDefGEN.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/British/gearUK40.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/British/gearUK44.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearFSJ40.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearFSJ44.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearFSJP40.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearFSJP44Jul.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearWHR39.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearWHR40.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearWHR42.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/German/gearWHR44.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/Japanese/gearJpn42.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/Japanese/gearJpn44.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/Russian/gearRus41.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/Russian/gearRus44.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/US/gearUS42.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/US/gearUS44.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/US/gearUSAB42.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/US/gearUSAB44.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/US/gearUSMC42.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/US/gearUSMC44.sqf
Labels: Refactor

#22 Split the Russian gearDefs
  missions/2PzD_Template_v3_0.VR/customization/gearLoadouts.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/Russian/gearDefNKVD.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/Russian/gearDefRusRegular.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/Russian/gearDefRusWeapons.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/Russian/gearDefRusWinter.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/Russian/gearRus41.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/Russian/gearRus44.sqf
Labels: bug, v3.0 Phase 1, Refactor

#25 Clean-up and some refactor work
  missions/2PzD_Template_v3_0.VR/core/init.sqf
  missions/2PzD_Template_v3_0.VR/customization/gearLoadouts.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/British/gearDefUK.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/Generic/gearDefEquipmentSets.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/German/gearDefGer.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/German/gearDefGerAfrica.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/German/gearDefGerLuft.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/German/gearDefGerMisc.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/German/gearDefGerRegular.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/German/gearDefGerWeapons.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/German/gearDefGerWinter.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/Russian/gearDefNKVD.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/Russian/gearDefRus.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/Russian/gearDefRusRegular.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/Russian/gearDefRusWeapons.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/Russian/gearDefRusWinter.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/US/gearDefUS.sqf
  missions/2PzD_Template_v3_0.VR/mission.sqm
Labels: Refactor, gear definitions

#26 Japanese gearDef changes
  compositions/!2PzD_Jpn_42/composition.sqe
  compositions/!2PzD_Jpn_44/composition.sqe
  missions/2PzD_Template_v3_0.VR/customization/gearLoadouts.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/Japanese/gearDefJapUniforms.sqf
  missions/2PzD_Template_v3_0.VR/customization/geardefs/Japanese/gearDefJapWeapons.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/Japanese/gearJpn42.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/Japanese/gearJpn44.sqf
Labels: v3.0 Phase 1, v3.0 Phase 2, Refactor, gear definitions, loadouts

#28 Typo in Rus44 Loadout
  missions/2PzD_Template_v3_0.VR/customization/loadouts/Russian/gearRus44.sqf
Labels: invalid, loadouts

#30 Changed equipment on some leader units
  missions/2PzD_Template_v3_0.VR/customization/loadouts/Russian/gearRus41.sqf
  missions/2PzD_Template_v3_0.VR/customization/loadouts/Russian/gearRus44.sqf
Labels: loadouts
